name: Validate

on:
  push:

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install tools
        uses: jdx/mise-action@v2
      - name: clj-kondo
        run: mise run lint
      - name: cljfmt
        run: mise run fmt:check

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install tools
        uses: jdx/mise-action@v2
      - name: Cache deps
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
          key: deps-${{ hashFiles('deps.edn') }}
      - name: Run tests
        run: mise run test

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build image
        run: docker build .
