name: Validate

on:
  push:

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install clojure tools
        uses: jdx/mise-action@v2
        
      - name: Lint
        run: clj-kondo --lint src test

  tests:
    runs-on: ubuntu-latest
    needs: [ lint ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install clojure tools
        uses: jdx/mise-action@v2

      - name: Run tests
        run: clojure -X:test
