name: Validate

on:
  push:

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@4.0
        with:
          cli: 1.11.3
          clj-kondo: 2024.05.24
      - name: Lint
        run: make lint

  tests:
    runs-on: ubuntu-latest
    needs: [ lint ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@4.0
        with:
          cli: 1.11.3

      - name: Run tests
        run: make test
